// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYbKgOp7SVciagXvbZ653BfOD9ifsJZI',
    appId: '1:226706929236:web:f62b2506e2ba497bfcdfc1',
    messagingSenderId: '226706929236',
    projectId: 'auth-4c70e',
    authDomain: 'auth-4c70e.firebaseapp.com',
    storageBucket: 'auth-4c70e.appspot.com',
    measurementId: 'G-DP2QRZHF1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgGtMToSazSzj0ZrTWVlN4JhJbZwVdfk',
    appId: '1:226706929236:android:365b7149b76a9abefcdfc1',
    messagingSenderId: '226706929236',
    projectId: 'auth-4c70e',
    storageBucket: 'auth-4c70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOuC15lmHnZRBLCBTtI0K-wQmph2GCrkw',
    appId: '1:226706929236:ios:036f5264ced3c224fcdfc1',
    messagingSenderId: '226706929236',
    projectId: 'auth-4c70e',
    storageBucket: 'auth-4c70e.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOuC15lmHnZRBLCBTtI0K-wQmph2GCrkw',
    appId: '1:226706929236:ios:036f5264ced3c224fcdfc1',
    messagingSenderId: '226706929236',
    projectId: 'auth-4c70e',
    storageBucket: 'auth-4c70e.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoYbKgOp7SVciagXvbZ653BfOD9ifsJZI',
    appId: '1:226706929236:web:7ffbfa27385a1921fcdfc1',
    messagingSenderId: '226706929236',
    projectId: 'auth-4c70e',
    authDomain: 'auth-4c70e.firebaseapp.com',
    storageBucket: 'auth-4c70e.appspot.com',
    measurementId: 'G-LEGE0VJM81',
  );
}
